"""Digital twins. v1 is persona cards + judges, not a causal model of a user base.

Each card is a *behavior*, not a demographic slogan. Grounded in
r/audiodrama, r/PocketFMReddit, Trustpilot, and Play Store complaints
from the last six months: coin walls, mid-sentence ads, unpaid mysteries,
generated coffee talk, yelling mixes, and kitchens flattened into English.
"""

from __future__ import annotations

PERSONAS = [
    {
        "id": "commute_meera",
        "name": "Meera, 24, dual-language commute",
        "cohort": "high_retention",
        "patience_exposition_sec": 90,
        "needs_choice_by_min": 8,
        "cliff_sensitivity": 0.8,
        "session_min": 14,
        "language": "Gujarati-English",
        "coin_sensitive": True,
        "skip_if": "mid-sentence ad or same-voice two characters",
        "stays_if": "character makes a costly choice before minute 8",
    },
    {
        "id": "night_arun",
        "name": "Arun, 31, last episode before sleep",
        "cohort": "high_retention",
        "patience_exposition_sec": 120,
        "needs_choice_by_min": 10,
        "cliff_sensitivity": 0.9,
        "session_min": 12,
        "language": "Hindi",
        "coin_sensitive": False,
        "skip_if": "mystery added with no payoff, or a yelling mix",
        "stays_if": "one secret paid, one new question left",
    },
    {
        "id": "skeptic_priya",
        "name": "Priya, 19, drops generated-sounding talk",
        "cohort": "low_retention",
        "patience_exposition_sec": 60,
        "needs_choice_by_min": 6,
        "cliff_sensitivity": 0.5,
        "session_min": 8,
        "language": "English",
        "coin_sensitive": True,
        "skip_if": "characters explain the coffee they are drinking",
        "stays_if": "speech patterns differ and a private monologue exists",
    },
    {
        "id": "binge_dev",
        "name": "Dev, 27, ten episodes a night",
        "cohort": "high_retention",
        "patience_exposition_sec": 150,
        "needs_choice_by_min": 9,
        "cliff_sensitivity": 0.7,
        "session_min": 22,
        "language": "Hindi",
        "coin_sensitive": False,
        "skip_if": "arc repeats the same reveal for 170 episodes",
        "stays_if": "each episode moves a relationship vector",
    },
    {
        "id": "ad_hater_leo",
        "name": "Leo, 34, r/audiodrama refugee",
        "cohort": "low_retention",
        "patience_exposition_sec": 80,
        "needs_choice_by_min": 7,
        "cliff_sensitivity": 0.6,
        "session_min": 11,
        "language": "English",
        "coin_sensitive": True,
        "skip_if": "ad in the middle of a threat line or 5 min bumper on an 11 min show",
        "stays_if": "break only after an emotional beat",
    },
    {
        "id": "nani_radio",
        "name": "Nani radio, 58, wants to hear herself",
        "cohort": "high_retention",
        "patience_exposition_sec": 180,
        "needs_choice_by_min": 12,
        "cliff_sensitivity": 0.4,
        "session_min": 15,
        "language": "Gujarati",
        "coin_sensitive": True,
        "skip_if": "kitchen flattened into generic English",
        "stays_if": "mother tongue stays in the kitchen",
    },
    {
        "id": "coin_rhea",
        "name": "Rhea, 29, has been burned by coin walls",
        "cohort": "low_retention",
        "patience_exposition_sec": 70,
        "needs_choice_by_min": 7,
        "cliff_sensitivity": 0.85,
        "session_min": 13,
        "language": "English",
        "coin_sensitive": True,
        "skip_if": "cliff exists only to sell the next coin, payoff never lands",
        "stays_if": "the paid minute actually answers something",
    },
]
